name: Validate

on: [push, pull_request_target]

jobs:
  getNodeVersion:
    uses: gagoar/github-app-installation-token/.github/workflows/node_version.yml@main

  buildCli:
    name: Run build-cli
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - uses: actions/checkout@v2
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-cli
      - name: use cli
        run: |
          PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"
          cli/cli.js \
             --appId ${{ secrets.APP_ID }} \
             --installationId ${{ secrets.INSTALLATION_ID }} \
             --privateKey="$PRIVATE_KEY"
