name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  getNodeVersion:
    uses: gagoar/github-app-installation-token/.github/workflows/node_version.yml@gg/sorting-out-workflows

  lint:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - run: npm install
      - run: npm run lint
